allowBuilds:
  esbuild: true
  workerd: true
peerDependencyRules:
  allowedVersions:
    vite: 0.2.9
minimumReleaseAgeExclude:
  - miniflare@4.20260722.1 || 5.20260804.1-alpha
  - "@voidzero-dev/vite-plus-core@0.2.9"
  - vite-plus@0.2.9
  - wrangler@4.121.0
  - "@voidzero-dev/vite-plus-darwin-arm64@0.2.9"
  - "@voidzero-dev/vite-plus-darwin-x64@0.2.9"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.9"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.2.9"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.2.9"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.2.9"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.9"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.2.9"
